### ISSUE TITLE
Why MLP's parameters set 0

### ISSUE THREAD

**Issue by DrRyanHuang** [CASIA-IVA-Lab/Obj2Seq#5]
https://github.com/CASIA-IVA-Lab/Obj2Seq/blob/a81484ef61d692e8d2b3f88e58c6df8344a50131/models/predictors/unified_seq_head.py#L106-L114

Hi, Thanks for your helpful code! 
Could you please tell me why the parameters of MLP are set to 0? Why not Normal init or others?

**Comment by volgachen** [comment]
Hello, we just follow the existing initialization as in [Deformable DETR](https://github.com/fundamentalvision/Deformable-DETR/blob/main/models/deformable_detr.py#L89).
I suppose these initializations would make little difference.
With zero-init, the model will output exactly a bounding box around the reference point before training.
